name: Deploy to Sakura

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. リポジトリのコードをチェックアウト（ダウンロード）
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. SSHのセットアップ
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_rsa

    # 3. rsyncでファイルをサーバーに同期
    - name: Sync files
      run: |
        rsync -avz --delete \
        -e "ssh -o StrictHostKeyChecking=no" \
        ./ ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/home/${{ secrets.SERVER_USERNAME }}/www/
