name: Deploy to Sakura

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # リポジトリのクローン
      - name: Checkout code
        uses: actions/checkout@v3

      # Node.js のセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # パッケージのインストール
      - name: Install dependencies
        run: npm install

      # ビルド
      - name: Build project
        run: npm run build

      # distフォルダをサーバーにアップロード
      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          server-ftp-pasv: true
          local-dir: dist/  # アップロードするローカルフォルダ（最後には/をつけないとエラーが出る）
          server-dir: /www/  # サーバー上のアップロード先
